-- MySQL Script generated by MySQL Workbench
-- Fri Dec  9 07:08:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inkautility
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inkautility
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inkautility` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `inkautility` ;

-- -----------------------------------------------------
-- Table `inkautility`.`HARDWARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`HARDWARE` (
  `idHARDWARE` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idHARDWARE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`EMPRESA` (
  `idEMPRESA` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEMPRESA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`AÑO_LANZAMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`AÑO_LANZAMIENTO` (
  `idAÑO_LANZAMIENTO` INT NOT NULL AUTO_INCREMENT,
  `AÑO` YEAR NOT NULL,
  PRIMARY KEY (`idAÑO_LANZAMIENTO`),
  UNIQUE INDEX `AÑO_UNIQUE` (`AÑO` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`USUARIO` (
  `idUSUARIO` INT NULL AUTO_INCREMENT,
  `NOMBRES` VARCHAR(45) NOT NULL,
  `APELLIDOS` VARCHAR(45) NOT NULL,
  `DNI` CHAR(8) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `PASSWORD` VARBINARY(100) NOT NULL,
  `GENERO` BIT NOT NULL,
  `MOVIL` CHAR(9) NOT NULL,
  PRIMARY KEY (`idUSUARIO`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) ,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) ,
  UNIQUE INDEX `MOVIL_UNIQUE` (`MOVIL` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`AREA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`AREA` (
  `idAREA` INT NOT NULL AUTO_INCREMENT,
  `NomArea` VARCHAR(45) NOT NULL,
  `img` BLOB NULL,
  PRIMARY KEY (`idAREA`),
  UNIQUE INDEX `CATEGORIA_UNIQUE` (`NomArea` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`VESION_OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`VESION_OS` (
  `idVESION_OS` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `ID_OS` INT NULL,
  PRIMARY KEY (`idVESION_OS`),
  UNIQUE INDEX `NOMBRE_UNIQUE` (`NOMBRE` ASC) ,
  INDEX `FK_OS_idx` (`ID_OS` ASC) ,
  CONSTRAINT `FK_OS`
    FOREIGN KEY (`ID_OS`)
    REFERENCES `inkautility`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`CATEGORIA` (
  `idCategoria` INT NOT NULL,
  `CategoriaNom` VARCHAR(45) NOT NULL,
  `img` BLOB NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `CategoriaNom_UNIQUE` (`CategoriaNom` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`SOFTWARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`SOFTWARE` (
  `idSOFTWARE` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `imgS` BLOB NULL,
  `DESCRIPCION` VARCHAR(65) NULL,
  `ID_EMPRESA` INT NULL,
  `ID_Categorias` INT NULL,
  PRIMARY KEY (`idSOFTWARE`),
  INDEX `FK_EMPRESA_idx` (`ID_EMPRESA` ASC) ,
  INDEX `FK_CATEGORIAS_idx` (`ID_Categorias` ASC) ,
  CONSTRAINT `FK_EMPRESA`
    FOREIGN KEY (`ID_EMPRESA`)
    REFERENCES `inkautility`.`EMPRESA` (`idEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CATEGORIAS`
    FOREIGN KEY (`ID_Categorias`)
    REFERENCES `inkautility`.`CATEGORIA` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`VERSION_SOFTWARE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`VERSION_SOFTWARE` (
  `idVERSION_SOFTWARE` INT NOT NULL AUTO_INCREMENT,
  `VERSION` VARCHAR(45) NOT NULL,
  `W` TEXT NULL,
  `L` TEXT NULL,
  `M` TEXT NULL,
  `ID_AÑO` INT NULL,
  `ID_SOFTWARE` INT NULL,
  PRIMARY KEY (`idVERSION_SOFTWARE`),
  INDEX `FK_AÑO_idx` (`ID_AÑO` ASC) ,
  INDEX `FK_SOFTWARE_idx` (`ID_SOFTWARE` ASC) ,
  CONSTRAINT `FK_AÑO`
    FOREIGN KEY (`ID_AÑO`)
    REFERENCES `inkautility`.`AÑO_LANZAMIENTO` (`idAÑO_LANZAMIENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SOFTWARE`
    FOREIGN KEY (`ID_SOFTWARE`)
    REFERENCES `inkautility`.`SOFTWARE` (`idSOFTWARE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`DISPOSITIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`DISPOSITIVO` (
  `idDISPOSITIVO` INT NOT NULL AUTO_INCREMENT,
  `ID_HARDWARE` INT NULL,
  `ID_VERSION_OS` INT NULL,
  PRIMARY KEY (`idDISPOSITIVO`),
  INDEX `FK_HARDWARE_idx` (`ID_HARDWARE` ASC) ,
  INDEX `FK_VERSION_OS_idx` (`ID_VERSION_OS` ASC) ,
  CONSTRAINT `FK_HARDWARE`
    FOREIGN KEY (`ID_HARDWARE`)
    REFERENCES `inkautility`.`HARDWARE` (`idHARDWARE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VERSION_OS`
    FOREIGN KEY (`ID_VERSION_OS`)
    REFERENCES `inkautility`.`VESION_OS` (`idVESION_OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inkautility`.`INKA_TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inkautility`.`INKA_TABLE` (
  `idINKA_TABLE` INT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT NULL,
  `ID_AREA` INT NULL,
  `ID_DISPOSITIVO` INT NULL,
  `ID_V_SOFTWARE` INT NULL,
  PRIMARY KEY (`idINKA_TABLE`),
  INDEX `FK_USUARIO_idx` (`ID_USUARIO` ASC) ,
  INDEX `FK_AREA_idx` (`ID_AREA` ASC) ,
  INDEX `FK_DISPOSITIVO_idx` (`ID_DISPOSITIVO` ASC) ,
  INDEX `FK_V-SOFTWARE_idx` (`ID_V_SOFTWARE` ASC) ,
  CONSTRAINT `FK_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `inkautility`.`USUARIO` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AREA`
    FOREIGN KEY (`ID_AREA`)
    REFERENCES `inkautility`.`AREA` (`idAREA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DISPOSITIVO`
    FOREIGN KEY (`ID_DISPOSITIVO`)
    REFERENCES `inkautility`.`DISPOSITIVO` (`idDISPOSITIVO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_V_SOFTWARE`
    FOREIGN KEY (`ID_V_SOFTWARE`)
    REFERENCES `inkautility`.`VERSION_SOFTWARE` (`idVERSION_SOFTWARE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
